[package]
name = "rq"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.42"
uuid = { version = "1.18.1", features = ["v4"] }
regex = "1.12.2"
ndarray = { version = "0.17.1", features = ["rayon", "std"] }
